rootfs_utils.jl

If the build is a pull request build, then we won't actually be creating the tarball, so it doesn't really make sense to print the path where the tarball would have been.

Logging: during `pull_request` builds, don't print the `tarball_path` in the `@info` message

---

Project.toml

1. In the `/Project.toml` file, add a `[compat]` entry for `julia`

Add a `[compat]` entry for `julia`

---

images/buildkite_agent_linux.jl
images/package_linux.jl
images/package_musl.jl

I was accidentally including the `.jl` file extension in the `tarball_name`.
Before this PR, an example `tarball_name` is:
- `buildkite_agent_linux.jl.x86_64.tar.gz`
After this PR, an example `tarball_name` is:
- `buildkite_agent_linux.x86_64.tar.gz`

Fix a small bug with the automatic construction of the `tarball_name`

---

Manifest.toml
Project.toml

The `test_rootfs.jl` script uses the Sandbox.jl package, so we might as well add it as a dependency to the environment.

Add the Sandbox.jl package as a dependency to the environment

---

.github/workflows/build.yml
images/llvm_passes.jl

In the long term, we probably will want to get everything working with one of the `package` images, e.g. `package_linux`.
But in the short term, it will be easiest to use the `llvm_passes.x86_64` image for the `analyzegc` and `asan` builders.

Back for a limited time only: the `llvm_passes` image

---

rootfs_utils.jl

That way, we can see what the filename of the tarball file _would have been_, even in PR builds.

Always print at least the `basename` of the `tarball_path`, even if we aren't actually creating the tarball file

---

README.md

This repository is home to the rootfs image definitions, but all other CI configuration files live in the `.buildkite` directory in the Julia repository, so we should link to there.
For symmetry, the `.buildkite/README.md` file in the Julia repository already links to this repository.

README: add a link to the `.buildkite` directory in the Julia repository

---

images/package_linux.jl

Otherwise, the `llvm_passes` builder (which now uses this image) won't be able to find `python` in the path.

`package_linux`: install both the `python` and `python3` packages from `apt`

---

rootfs_utils.jl

The `force_overwrite` option makes it too easy to accidentally overwrite an existing release artifact.
If a user really needs to overwrite an existing artifact, they can still do so by taking the following steps:
1. Go to https://github.com/JuliaCI/rootfs-images/releases
2. Click on the release in question.
3. Click the "Edit release" button.
4. Scroll down to the bottom of the page, where there is a list of all of the existing artifact files for that release.
5. Next to the artifact file that you want to overwrite, click on the "X" to delete that file.
6. At the bottom of the page, click on the green "Update release" button, which will cause the file to be deleted.
7. Now that the file has been deleted, you can run the `upload_rootfs_image` function to upload the new artifact file.
That …

`rootfs_utils`: remove the `force_overwrite` keyword argument

---

.github/workflows/build.yml

This allows us to simplify our branch protection settings. We can just have the `main` branch require the `all` status check. That way, we don't need to edit the branch protection settings every time we add, remove, or rename an image.

CI: add a dummy "all" job that depends on all of the actual build jobs

---

.github/workflows/build.yml
images/package_linux_qemu.jl

The `package_linux_qemu` images are just like the `package_linux` images, except that the `package_linux_qemu` images also include `qemu` inside the sandbox.

Add the `package_linux_qemu` rootfs images

---

.github/workflows/build.yml
images/agent_linux.jl
images/llvm_passes.jl
images/package_linux.jl
images/package_linux_qemu.jl
images/package_musl.jl
images/tester_linux.jl
images/tester_musl.jl
rootfs_utils.jl
test_rootfs.jl

This is just a simple sanity check to make sure that the rootfs image that we build can be used with Sandbox.jl.

CI: after building the image, test that it can be used with Sandbox.jl

---

test_rootfs.jl

When downloading an artifact, immediately throw an exception if there is a hash mismatch

---

.github/workflows/build.yml

According to the GitHub documentation (https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token):
> You can use the `permissions` key in your workflow file to modify permissions for the `GITHUB_TOKEN` for an entire workflow or for individual jobs. This allows you to configure the minimum required permissions for a workflow or job. When the `permissions` key is used, all unspecified permissions are set to no access, with the exception of the `metadata` scope, which always gets read access.
Therefore, if we just set `contents: write`, all of the other permissions will automatically be set to no access.

CI: Simplify the `permissions` key in the workflow file

---

.github/workflows/build.yml
images/agent_linux.jl
images/debian_minimal.jl
images/llvm_passes.jl
images/package_linux.jl
images/package_linux_qemu.jl
src/build/debian.jl

The `debian_minimal` image contains no packages.
We can use this e.g. for testing in the Sandbox.jl test suite. cc: @staticfloat

Add the `debian_minimal` rootfs image

---

.github/workflows/build.yml
src/build/common.jl

On builds triggered by pushes to `main`, upload the rootfs image `.tar.gz` files as GitHub Actions Artifacts

---

test_rootfs.jl

The default tmpfs size (1G) is not big enough to build Julia from source.

In the `test_rootfs.jl` script, increase the tmpfs size to 2G

---

src/build/alpine.jl

This will prevent CI from randomly breaking because they changed something upstream.

Alpine: when downloading the Alpine rootfs, instead of providing a branch name (e.g. `v3.13`), provide the full commit hash

---

src/test_img/args.jl

Now that we have the optional `--tmpfs-size` command-line argument, it is easy for users to set whatever tmpfs size they want. So let's default to something smaller, i.e. 1G, and users that need more can easily set a larger tmpfs size.

`test_rootfs.jl` script: default to a tmpfs size of 1G

---

.github/workflows/linux.yml
.github/workflows/windows.yml
windows/package_win32/Dockerfile
windows/package_win64/Dockerfile

This is just a really simple example to demonstrate that we can use GitHub Actions to build Docker images with Docker for Windows.

Add an example of using CI to build a Windows Docker image

---

linux/agent_linux.jl
linux/debian_minimal.jl
linux/llvm_passes.jl
linux/package_linux.jl
linux/package_musl.jl
linux/pkgserver_logsync.jl
linux/tester_linux.jl
linux/tester_musl.jl
src/build_img/alpine.jl
src/build_img/args.jl
src/build_img/common.jl
src/build_img/debian.jl
test_rootfs.jl

This PR adds the optional `--no-archive` command-line flag when building rootfs images. This flag does not take any arguments.
When the `--no-archive` command-line flag is NOT provided (the default behavior), then the tarball WILL be created.
When the `--no-archive` command-line flag is provided, then the tarball will NOT be created.
When I'm working locally, my workflow looks like this:
1. Build the rootfs image
2. Enter the rootfs image, and run some commands (e.g. try to build Julia or run the Julia tests)
3. Encounter some kind of problem
4. Edit the rootfs image definition
5. Re-build the rootfs image with the new definition
6. Enter the new rootfs image
7. Repeat the cycle
When working in this cycle, I don't actually need to create the tarball files. So it's much faster for me if I …

Add the ability to skip tarball creation when developing locally

---

.github/workflows/linux.yml

I'm running into segfaults when trying to build this via qemu. Let's disable it temporarily, and then re-enable it once we've fixed the issue.

Temporarily disable building the `package_linux.aarch64` image

---

linux/python_latex_kitchen_sink.jl
linux/tester_linux.jl
linux/tester_musl.jl

I know that some people prefer to use `lldb` instead of `gdb`. So let's give the user the choice

Add `lldb` to every rootfs image that currently has `gdb`

---

linux/python_latex_kitchen_sink.jl

`zip` is required for certain SciML tests

Add `zip` to python_latex_kitchen_sink

---

src/test_img/args.jl

After all, the `--override-tmp-dir` flag is just for the `test_rootfs.jl` script, so I think it's fine for `--override-tmp-dir true` to be the default.
It's easy enough for the user to pass `--override-tmp-dir false` if they don't like the default value.

Keep `true` as the default value for the `--override-tmp-dir` flag

---

src/utils/chroot.jl

This can be useful if e.g. you want to `read(cmd, String)` instead of just doing `run(cmd)`.

Add the `chroot_command` and `root_chroot_command` utility functions for constructing the `Cmd` objects but not actually running them

---

linux/agent_linux.jl
linux/package_linux.jl
linux/rr.jl

This should make calls to the `my_chroot` closures less verbose and more readable.

Reduce some duplication when using the `root_chroot` function

---

src/test_img/args.jl
test_rootfs.jl

Closes #164 
The user can of course do this manually, but it's nice to be able to automate it.

`test_rootfs.jl`: add a command-line option to automatically mount Julia from the outside world into the sandbox

---

linux/package_linux.jl

This is the first step in a lot of work, but let's get this stable and then move on to the rest.
@DilumAluthge @brenhinkeller if this works as I think it should, it should unblock our forward momentum on getting linux `x86_64` moved to buildkite.

Use custom GCC 9 and glibc 2.12.2 for `package_linux` on `x86_64-linux-gnu`

---

src/build_img/common.jl

Hopefully this will eliminate the problems we have with out-of-date
indexes being embedded within our rootfs images.

Remove `/var/lib/apt/lists/*` on debian systems

---

linux/tester_linux.jl
linux/tester_musl.jl

I want to actually use the `tester` images to run our tests.

Add `git` and `make` to our `tester` images

---

linux/package_linux.jl

This ensures that we can always run a program built with `g++` within
the packager.  This occurs because the GCC we're shipping has a
(slightly) newer `libstdc++` than the one that ships with the underlying
OS.

Copy our GCC's `libstdc++` over the system-wide `libstdc++`.

---

linux/tester_linux.jl

The `Pkg` tests require `kill`

We need `procps` on `tester_linux`

---

linux/llvm_passes.jl

In https://github.com/JuliaCI/julia-buildkite/pull/102, when we trying to build `libunwind`, it fails with `cannot find -lz`, so hopefully this will fix it.

Add zlib to the `llvm_passes` image

---

linux/package_linux.jl

For some reason, the libstdc++ in our glibc compiler shard requires 2.19.  I'm not sure why this is the case on powerpc64le and not on x86_64, but I don't have the will to track it down right now.  The difference between 2.17 and 2.19 on powerpc64le systems should be minor, so let's just see if this fixes packaging on power.

Use glibc 2.19 on powerpc64le

---

linux/aws_uploader.jl

Example: https://buildkite.com/julialang/julia-release-1-dot-8/builds/76#018106cc-df73-4176-9b61-1750bfb6a631/474-476
Note that while this isn't a fatal error for us (since the value is not used in the upload job, only the build job), I don't like it.  :P

It's often useful to have `make` as a part of the aws uploader

---

linux/tester_linux.jl
src/test_img/args.jl
test_rootfs.jl

I want to upload compressed core dump files, `zstd` does a really good job of compressing them and it's fast.

Add `zstd` to `tester_linux`

---

linux/tester_musl.jl

Add `zstd` to `musl` as well

---

linux/llvm_passes.jl

We use this image for our "from-source" build on CI, so we need these debugging tools as well.

Add debugging utilities to `llvm_passes`

---

linux/debian_minimal.jl
linux/tester_linux.jl
src/build_img/debian.jl

We need this for the locale tests in the Julia test suite.
We don't add this to `tester_musl` because locales there are broken.
X-ref: https://musl.openwall.narkive.com/kO1vpTWJ/setlocale-behavior-with-missing-locales

Add Korean locale to `tester_linux`

---

linux/aws_uploader.jl

This is so that we can `git push` things.

Add openssh to aws_uploader

---

linux/python_latex_kitchen_sink.jl

`wget` is not needed since `curl` can be used instead. `make` is required for building cmdstan.

Remove `wget` and add `make`

---

linux/llvm_passes.jl
linux/package_linux.jl
linux/pkgserver_logsync.jl
src/build_img/debian.jl

Bullseye is the current stable release of Debian, and Buster is the oldstable (previous stable release). So let's upgrade our images from Buster to Bullseye.

Upgrade all glibc Linux images from Debian Buster to Debian Bullseye

---

.github/workflows/linux.yml
linux/latex.jl

Let's see if `--no-install-recommends` helps us keep this under 5GB.

Add the `latex.x86_64` image for building the PDF docs on Buildkite

---

.github/workflows/windows.yml
windows/package_win32/Dockerfile
windows/package_win64/Dockerfile

Chengyu has kindly forged a path forward for us to use windows docker containers on CI, let's import his win64 packaging docker container here.
This code gratefully copied from: https://github.com/inkydragon/msys2-mingw-w64
I have dropped the "Unlicense" SPDX modifier and kept only MIT, to match the rest of this repository.

Import inkydragon's windows docker build

---

.github/workflows/windows.yml
windows/package-i686/Dockerfile
windows/package-x86_64/Dockerfile

We need to use the SJLJ exception handling technique when targeting win32, but because msys2 defaults to dw2, we can't use pacman to install their compiler.  Instead, we use a prebuilt binary from elsewhere on the internet.

Install custom `SJLJ` toolchain on win32

---

.github/workflows/linux.yml
linux/xvfb.jl

This is needed for CI on the PkgEval.jl repo. See https://github.com/JuliaCI/PkgEval.jl/pull/144

Add the `xvfb` rootfs image

---

linux/tester_linux.jl

Jameson wants to be able to run `netstat` and such, which seems like a good idea.

Add `net-tools` to `tester_linux`

---

linux/agent_linux.jl

While the outer agent images are intentionally quite bare, the compression/decompression speed of `zstd` makes it extremely attractive to use by default within plugins.  I intend to use it in `coppermind` by default, so I'm adding it to the bare agent image for now, with a future "JLL installation plugin" to come.

Add `zstd` to `agent_linux` images

---

linux/package_linux.jl

This helps us to ensure that we've got the right version of binutils as well

Print out `ld` as well

---

linux/package_linux.jl

We've been talking about this for ages, our new libuv builds require this, so let's actually do it.  BB can catch up later.
---
Drops support for: RHEL 6, CentOS 6
Keeps support for: RHEL 7, CentOS 7

Bump x86_64 and i686 minimum glibc version to v2.17 (and thus drop support for RHEL 6 and CentOS 6, but keep support for RHEL 7 and CentOS 7)

---

linux/package_musl.jl

We need this when building from source.

Add `patch` to musl builders

---

linux/rr.jl

Ref https://github.com/rr-debugger/rr/pull/3689

Add `lldb` to the rootfs image used in rr's CI

---

README.md

As described does not work:
```
kristofferc@deepsea3:~/rootfs-images$ julia --project test_rootfs.jl --url https://github.com/JuliaCI/rootfs-images/releases/download/v3.18/package_linux.x86_64.tar.gz
┌ Warning: Hash not provided; this will download the tarball, then fail, so you can see the true hash
└ @ RootfsUtils ~/rootfs-images/src/utils/args.jl:16
[ Info: Artifact did not exist locally, downloading
[ Info: Unpacking /tmp/jl_GL0NUR2BUD-download.gz into /home/kristofferc/.julia/artifacts/jl_vf9Tmh...
ERROR: LoadError: Tree Hash Mismatch!
Expected git-tree-sha1:   0000000000000000000000000000000000000000
Calculated git-tree-sha1: 23cfae2cfdeeb8e25484388241d2d723144618a1
Stacktrace:
[1] ensure_artifact_exists_locally(; treehash::Base.SHA1, url::String)
@ RootfsUtils …
```

also provide URL with the tree hash

---

windows/package-i686/Dockerfile
windows/package-x86_64/Dockerfile

This bumps the msys2 versions to see if this can fix the weird ASLR issue we've seen in windows builders. This does mean we will get very new compilers for windows, this is hopefully not an issue (glibc compatibility isn't a thing and we ship a very new libstdc++) 
It's GCC 13.2 for reference so it should be the same version libstdc++ that we have in julia since at least 1.10

Bump msys2 version to the latest release as an attempt to fix the weird ASLR issue

---

windows/package-i686/Dockerfile
windows/package-x86_64/Dockerfile

There are JLLs that require the Visual C++ redistributables, let's allow those JLLs to be used within these containers

[Windows] Install Visual C++ redistributables

---

linux/llvm_passes.jl

This fixes `make build-stats` failing when using the `llvm-passes` image, as the scheduled build does. https://github.com/JuliaCI/rootfs-images/pull/240 did the same thing for the `package-*` images

Add `time` to the `llvm_passes` image

---

linux/llvm_passes.jl

Should no longer be necessary after https://github.com/JuliaLang/julia/pull/57798 and https://github.com/JuliaLang/julia/pull/57792

Remove zlib from llvm_passes image
